### ISSUE TITLE
Sample to Pop: Additional Parameter

### ISSUE THREAD

**Issue by verma-priyanka** [verma-priyanka/pontiPy#10]
_Claire_
- The pontipy object should take an additional parameter if the dataframe is a sample
- By default, the input df will be a population df and stratum = NULL
-  For Sample to Population, stratum will be provided as a list

**Comment by wqtclaire** [comment]
[sampop.zip](https://github.com/verma-priyanka/pontiPy/files/5434174/sampop.zip)

**Comment by wqtclaire** [comment]
ooops ignore the picture lol I forgot to delete it. Basically it's an ipynb that uses the sample.csv.

**Comment by verma-priyanka** [comment]
Added to library

**Comment by verma-priyanka** [comment]
Added to library 11/20
